### ISSUE TITLE
Not actually published to pypi?

### ISSUE THREAD

**Issue by jbeluch** [douglas/toxiproxy-python#1]
Are there plans to publish this to pypi?

**Comment by douglas** [comment]
Hello @jbeluch! Sure! Will try to do that asap.

Sorry for the delay to reply your message, I've been pretty busy lately.

**Comment by grubert65** [comment]
Hi, this issue is quite important, as it prevents proper dependency management for packages that depend on this one.

**Comment by grubert65** [comment]
Hi @douglas,
I branched master, build a dist and shipped to pypi.org, so from now on the following:

pip install toxiproxy-python

should work on any python3 virtualenv. I have no grants to push my changes back, can you add me as project contributor ? Thank you.

**Comment by douglas** [comment]
Hello @grubert65!

Thanks a lot for your contribution for this project! Still very busy, so I'm really help for your help with this!

Can you push a PR with your changes so I can review them? I think there's quite a few things to merge on this library to be on par with Ruby version - I'll try to get into it as well.

**Comment by douglas** [comment]
And.... I couldn't get to it yet, I'll try to find some time to check the status on it this week but I would love some help to keep it moving if y'all are interested  =)

**Comment by douglas** [comment]
Closing this issue so I can hopefully give this project some love =)
