### ISSUE TITLE
General Status and Maintenance

### ISSUE THREAD

**Issue by esoterra** [douglas/toxiproxy-python#4]
Is this project being maintained, and will it ever be?
The last modification is 2 years ago and the documentation is incomplete.

**Comment by douglas** [comment]
Hello Kyle! Sorry for the delay - I haven't been working on it for a while but I can review pull-requests / improvements for it.

I intend to bring it to parity with Toxiproxy features at some point since it is being used by more and more people but it is not a priority at the moment.

**Comment by douglas** [comment]
I'm closing this issue since I'm getting back to the project so I can at least getting to feature parity with the Ruby client.
